### ISSUE TITLE
Needs a tutorial on how to setup

### ISSUE THREAD

**Issue by jermeister6** [VodBox/Ponderyier#1]
I am confused D:

**Comment by wongjoel** [comment]
There is now a tutorial for setting up node.js correctly at https://github.com/VodBox/Ponderyier/wiki/Setting-up-the-development-environment

**Comment by wongjoel** [comment]
Connecting to twitch is now explained [here](https://github.com/VodBox/Ponderyier/wiki/Connecting-to-Twitch)
